import type { StringsFile } from "../types";
import { targetsOf } from "../types";

const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");

export function renderWindowsResources(doc: StringsFile, language: string): string {
  const rows: string[] = [];
  for (const [key, entry] of Object.entries(doc.strings).sort(([a], [b]) => a.localeCompare(b))) {
    if (!targetsOf(entry).includes("windows")) continue;
    const forms = entry.plural?.[language] ?? entry.plural?.[doc.sourceLanguage];
    const categories = entry.plural ? [...new Set(Object.values(entry.plural).flatMap(forms => Object.keys(forms)))].sort() : [];
    const values = entry.plural
      ? categories.map(category => [`${key}_${category}`, forms?.[category as keyof typeof forms] ?? forms?.other ?? key])
      : [[key, entry.translations?.[language] ?? entry.translations?.[doc.sourceLanguage] ?? key]];
    for (const [name, text] of values) {
      rows.push(`  <data name="${escape(name!)}" xml:space="preserve"><value>${escape(text!)}</value></data>`);
    }
  }
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by localization/. Do not edit. -->\n<root>\n  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>\n  <resheader name="version"><value>2.0</value></resheader>\n${rows.join("\n")}\n</root>\n`;
}
